### ISSUE TITLE
Please add this patch to allow cross-compiling

### ISSUE THREAD

**Issue by fesc2000** [PeterPawn/privatekeypassword#1]
```
diff --git a/Makefile b/Makefile
index 63781b7..d78f8e8 100644
--- a/Makefile
+++ b/Makefile
@@ -22,7 +22,7 @@ LIB_OBJS = $(LIB_SRCS:%.c=%.o)
 #
 # tools
 #
-CC = gcc
+CC = $(CROSS_COMPILE)gcc
 RM = rm
 AR = ar
 RANLIB = ranlib
```

**Comment by PeterPawn** [comment]
Sorry for the late answer, I forgot to add this repo to my own watch-list.

I'll change this with the next major revision ... I want to change the whole handling anyway and use the new (and fastest) approach, after I released the shell-based solution (years after the prior version ;-) ). It works now without any AVM component (the former solution had used libboxlib.so for 'securestore_get'). I will build a new library with the same interface and without references to anything else than the 'urlader environment', which is needed to get the 'maca' value.
